### ISSUE TITLE
Backend 설정 값들을 변수화

### ISSUE THREAD

**Issue by vntg-ldy** [ldy9037/terraform-backend#2]
GCS를 모듈로 생성하면 Bucket 명에 Prefix와 Region 값이 들어감.
 {prefix}-{region}-{name} 이런 형식인데, backend 구성에서 버킷명을 전달 받기 때문에 직접 하드코딩 하는 것보다는 변수명으로 받는 것이 좋을 것 같음. 

https://github.com/hashicorp/terraform/issues/13022
위 내용 보고 관련 변수들을 환경 변수로 분리해 조합해 사용하면 될 듯.

**Comment by ldy9037** [comment]
설정 값들을 환경변수로 변수화 하였고 -backend-config option으로 해당 값들을 지정해 주었음. 
지정한 내용은 아래 형식임.

export TF_VAR_region=asia-<REGION>
export TF_VAR_state_bucket_prefix=<PREFIX>
export TF_VAR_state_bucket_name=<BUCKET_NAME>

export TF_VAR_backend_bucket=${TF_VAR_state_bucket_prefix}-${TF_VAR_region}-${TF_VAR_state_bucket_name}
export TF_VAR_backend_prefix=<BACKEND_PATH>
